# -*- coding: utf-8 -*-
"""python project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ZK7U_zFEZOXgKTCEEzOPNPynw_tG8vS
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px



df=pd.read_csv("/content/hotel_bookings.csv")

df.shape

df.info()

df.isnull().sum()

df.drop(columns=["company","agent"],inplace=True)

df.nunique()

# total no.of reservations in hotels
df["hotel"].value_counts()

# no.of reservations canceled or not
df["is_canceled"].value_counts()

# percentage of cancellations in city and resort hotel

data=pd.crosstab(df["is_canceled"],df["hotel"],normalize="columns")*100
data

df[df["hotel"]=="Resort Hotel"]["is_canceled"].value_counts()

df["lead_time"].value_counts().head(10)

df["children"].value_counts()

df["meal"].value_counts()

# types of market segment
df["market_segment"].value_counts()

df["deposit_type"].value_counts()

# reservations acc to room type
df["reserved_room_type"].value_counts()

# types of customer
df["customer_type"].value_counts()

df["reservation_status"].value_counts()

# reservations in different countries

df["country"].value_counts()

df["meal"].replace("Undefined","SC",inplace=True)

# inaccurate data

subset=df[(df["adults"]==0 )& (df["babies"]==0 )& (df["children"]==0)]
subset[["adults","babies","children"]]
deleted=(df["adults"]==0 )& (df["babies"]==0 )& (df["children"]==0)
df=df[~deleted]

df=df[df["adr"]<5000]

# no.of reservations cancelled or not
sns.countplot(data=df,x="is_canceled",palette="Set3")
plt.ylabel("no.of reservation")
plt.title("reservations status count")

# cancellations in resort and city hotel

sns.countplot(data=df,x="hotel",hue="is_canceled",palette="pastel")
plt.ylabel("no.of reservations")
plt.title("reservation status of different hotel")

# new column-"month"

df["month"]=pd.to_datetime(df["reservation_status_date"]).dt.month_name()

df.drop(columns=["arrival_date_month"],inplace=True)

# reservations in different months
sns.countplot(data=df,x="month",hue="is_canceled",palette="viridis")
plt.xticks(rotation="vertical")
plt.xlabel("months",color="blue")
plt.ylabel("no.of reservations",color="blue")
plt.title("Reservations in months")
plt.show()

"""Most of the reservations were canceled in month of january and february and were confirmed in month of august and september



"""

# reservation confirmed data
df_n=df[df["is_canceled"]==0]
# reservation canceled data
df_y=df[df["is_canceled"]==1]
df_canceled=df_y.groupby("month")[["adr"]].sum().reset_index()

# Sum of Average daily Rate of cancelled reservations in differnet months

plt.figure(figsize=(10,5))
sns.barplot(data=df_canceled,x="month",y="adr")
plt.xticks(rotation="vertical")
plt.xlabel("months",color="green")
plt.ylabel("adr",color="green")

plt.show()

"""In month of january and february adr is highest when the most of reservations are cancelled"""

#where do the guest come from?
# top_10 countries

top_10=df["country"].value_counts()[:10]

plt.pie(top_10.values,autopct='%1.1f%%',labels=top_10.index)
plt.legend()
plt.show()

# top 10 countries with maximum cancellations

top_10=df_y["country"].value_counts()[:10]
plt.pie(top_10.values,autopct='%1.1f%%',labels=top_10.index)
plt.legend()
plt.show()

"""Most of the guest are from portugal and other countries in Europe and also maximum no.of cancellations are also from portugal"""

list=df["days_in_waiting_list"].value_counts().head(10).index.to_list()
df_new=df[df["days_in_waiting_list"].isin(list)]

# Bookings per market segment
sns.countplot(df,x="market_segment",hue="is_canceled")
plt.xticks(rotation="vertical")
plt.xlabel("market_segment",color="blue")
plt.ylabel("no. of reservations",color="blue")
plt.title("Bookings per segment",color="blue")
plt.show()

# percentage of people not getting reserved room type
(df.shape[0]-df[df["reserved_room_type"]==df["assigned_room_type"]].shape[0])/df.shape[0]*100

df_x=df[~(df["reserved_room_type"]==df["assigned_room_type"])]
df_x["is_canceled"].value_counts()
(801/13995)*100

# reservations acc to room_type
room_type=df.groupby("reserved_room_type")["reserved_room_type"].count()
plt.pie(room_type,labels=room_type.index,autopct='%1.1f%%')
plt.show()

df["reservation_status_date"]=pd.to_datetime(df["reservation_status_date"])

df["reservation_status_date"].value_counts()

# Adr by market segment and room type
fig,ax= plt.subplots(figsize=(15,8))
sns.barplot(df,x="market_segment",y="adr",hue="reserved_room_type",ax=ax)
plt.xticks(rotation="vertical")
plt.title("Adr by market segment and room type")
plt.show()

# Adr of resort and city hotel over a period of time
resort_hotel=df[df["hotel"]=="Resort Hotel"]
city_hotel=df[df["hotel"]=="City Hotel"]


resort_price=resort_hotel.groupby("reservation_status_date")[["adr"]].mean().reset_index()
city_price=city_hotel.groupby("reservation_status_date")[["adr"]].mean().reset_index()

resort_price["reservation_status_date"]=pd.to_datetime(resort_price["reservation_status_date"])

city_price["reservation_status_date"]=pd.to_datetime(city_price["reservation_status_date"])
resort_price=resort_price.sort_values("reservation_status_date")
city_price=city_price.sort_values("reservation_status_date")

plt.figure(figsize=(15,8))
plt.plot(resort_price["reservation_status_date"],resort_price["adr"],label="resort_hotel",color="green")
plt.plot(city_price["reservation_status_date"],city_price["adr"],label="city_hotel",color="red")
plt.xlabel("reservation_date",color="green")
plt.ylabel("adr",color="green")
plt.legend()
plt.show()

# customer_type

sns.countplot(df,x="customer_type",hue="is_canceled",palette="Set2")
plt.show()

# Effect of adr on cancellations


df_yes=df_y.groupby("reservation_status_date")[["adr"]].mean().reset_index()
df_not=df_n.groupby("reservation_status_date")[["adr"]].mean().reset_index()
df_yes["reservation_status_date"]=pd.to_datetime(df_yes["reservation_status_date"])
df_not["reservation_status_date"]=pd.to_datetime(df_not["reservation_status_date"])
df_yes=df_yes.sort_values("reservation_status_date")
df_not=df_not.sort_values("reservation_status_date")

plt.figure(figsize=(15,8))
plt.plot(df_yes["reservation_status_date"],df_yes["adr"],label="canceled")
plt.plot(df_not["reservation_status_date"],df_not["adr"],label="not_canceled")
plt.legend()
plt.xlabel("reservation_date")
plt.ylabel("Average daily rate")
plt.title("Average daily rates in hotels")

# effect of deposit type on cancellations
deposit_canceled_data=df.groupby("deposit_type")["is_canceled"].describe()
sns.barplot(deposit_canceled_data,x=deposit_canceled_data.index,y=deposit_canceled_data["mean"],palette="Set2")
plt.ylabel("cancellation % ")
plt.title("Effect of deposit type on cancellation")
plt.show()

print(pd.crosstab(df["is_repeated_guest"],df["is_canceled"],normalize="index")*100)
# percentage of repeated_guest who canceled the reservations
#==14%
# percentage of non repeated guest who canceled the reservations
#==37%
# people who have not previously booked any reservations cancelled most

df['required_car_parking_spaces'].value_counts()
# this shows that required car parking spaces is almost zero

# reservations with special requests
sns.countplot(df,x='total_of_special_requests',hue="is_canceled")
plt.show()
# this shows special requests are lesser in number but reservations with special requests are less likely to get cancelled

# how long do guests stay?
df["total_nights"]=df["stays_in_week_nights"]+df['stays_in_weekend_nights']
people_stay=df["total_nights"].value_counts()/df["total_nights"].count()*100
# percentage of guests who stays at hotel
fig,ax=plt.subplots(figsize=(15,8))
ax=plt.pie(people_stay,autopct='%1.1f%%',labels=people_stay.index)
plt.title("Length of stay",fontsize=16,color="green")
plt.show()

# Effect of lead time on cancellations
lead_time=df.groupby("lead_time")["is_canceled"].describe()
print(lead_time)
sns.regplot(lead_time,x=lead_time.index,y=lead_time["mean"]*100)
plt.ylabel("cancellation %")
plt.show()
#Bookings made a few days before the arrival date are rarely canceled, whereas bookings made over
#one year in advance are canceled very often.